# Generated by Django 3.2.4 on 2021-08-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_rename_categories_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categoryDesc',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
