# Generated by Django 3.2.4 on 2021-08-22 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('productID', models.BigAutoField(primary_key=True, serialize=False)),
                ('productSKU', models.CharField(max_length=200)),
                ('productName', models.CharField(max_length=300)),
                ('productPrice', models.DecimalField(decimal_places=2, max_digits=8)),
                ('productWeight', models.DecimalField(decimal_places=2, max_digits=8)),
                ('productCartDesc', models.TextField()),
                ('productShortDesc', models.TextField()),
                ('productLongDesc', models.TextField()),
                ('productCoverImage', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('productUpdateDate', models.TextField()),
                ('productStocks', models.FloatField(null=True)),
                ('productsDiscount', models.FloatField(null=True)),
                ('isProductAvailable', models.BooleanField()),
                ('productCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.categories')),
                ('sellerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
        ),
    ]
