# Generated by Django 3.2.4 on 2021-08-23 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('categories', '0002_rename_categories_category'),
        ('orderdetails', '0002_rename_orderdetails_orderdetail'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
