# Generated by Django 3.2.4 on 2021-08-22 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orderID', models.BigAutoField(primary_key=True, serialize=False)),
                ('orderDate', models.DateField()),
                ('orderShippedDate', models.DateField()),
                ('isOrderReturns', models.BooleanField(default=False)),
                ('orderReturnsReason', models.TextField(max_length=200, null=True)),
                ('orderTrackingNumber', models.TextField(max_length=200)),
                ('orderCustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
        ),
    ]
